### ISSUE TITLE
Need battery-9v.png

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/components#1]
...as used by https://github.com/raspberrypilearning/balloon-pi-tay-popper/blob/master/hardware.yml which means http://www.raspberrypi.org/learning/balloon-pi-tay-popper/requirements/ has a missing image.
(@bennuttall Is this the appropriate place for issues like this, or should they be filed against the individual resources?)

**Comment by bennuttall** [comment]
They should be (and are) filed in the resource repository: [balloon-pi-tay-popper #6](https://github.com/raspberrypilearning/balloon-pi-tay-popper/issues/6)

Sam's been working on them today. Should have all the make resource hardware components up tomorrow :)

**Comment by lurch** [comment]
> filed in the resource repository: balloon-pi-tay-popper #6

Whoops, dunno how I missed that! Sorry. Sam's been doing a great job :-)
