### ISSUE TITLE
Reed Switch

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/components#3]
@bennuttall @samalderhyde Please add a reed switch, used in weather station resource
https://cdn.sparkfun.com//assets/parts/1/7/8/4/08642-02-L.jpg

**Comment by samalderhyde** [comment]
Sure thing

**Comment by bennuttall** [comment]
Is this still todo?

**Comment by samalderhyde** [comment]
Yes! I'll do that tomorrow

On 5 Aug 2015, at 17:03, Ben Nuttall <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this still todo?

##
